_BASE_: ../Base-PSTdataset-SemanticSegmentation.yaml


DATASETS:
  IMS_PER_BATCH: &b 4

MODEL:
  SWIN:
    PRETRAINED: './pretrained_model/swinv2_large_patch4_window12_192_22k.pth'
    FROZEN_STAGE: 4
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    PRETRAINED_WINDOW_SIZE: [12,12,12,12]
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    USE_CHECKPOINT_LIST: [False,False,False,False]
    OUT_FEATURES:  ["res2", "res3", "res4", "res5"]
    MODEL_OUTPUT_ATTN: False

SOLVER:
  IMS_PER_BATCH: *b
  BACKBONE_MULTIPLIER: 4.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 20.0
    NORM_TYPE: 2.0
